### ISSUE TITLE
Omnisharp server fails to start

### ISSUE THREAD

**Issue by P-de-Jong** [tareqimbasher/NetPad#92] opened 2023-09-21 12:55 UTC
Just installed NetPad on Pop!_OS, getting an error: "OmniSharp Server failed to start".

![image](https://github.com/tareqimbasher/NetPad/assets/22365764/1463f901-c600-4036-aa16-06f3d3c38d2d)

Message from log file:
```
2023-09-21T14:23:00.7769721+02:00 [ERR] (PID: 101725|NetPad.Plugins.OmniSharp.Services.OmniSharpServerCatalog) Error occurred starting OmniSharp server
System.PlatformNotSupportedException: OS Architecture 'X64' is not supported. OS: (Linux 6.4.6-76060406-generic #202307241739~1694621917~22.04~ac5e1a8 SMP PREEMPT_DYNAMIC Wed S)
   at NetPad.Utilities.PlatformUtil.IsOsArchitectureSupported(Boolean throwIfNotSupported) in /home/tips/Source/TIPS/NetPad/src/Core/NetPad.Domain/Utilities/PlatformUtil.cs:line 38
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerDownloader.DownloadAsync(OSPlatform platform) in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerDownloader.cs:line 50
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerDownloader.DownloadAsync(OSPlatform platform) in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerDownloader.cs:line 93
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerLocator.GetServerLocationAsync() in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerLocator.cs:line 41
   at NetPad.Plugins.OmniSharp.Services.AppOmniSharpServer.StartOmniSharpServerAsync() in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/AppOmniSharpServer.cs:line 132
   at NetPad.Plugins.OmniSharp.Services.AppOmniSharpServer.StartAsync() in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/AppOmniSharpServer.cs:line 87
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerCatalog.<>c__DisplayClass7_1.<<StartOmniSharpServerAsync>b__1>d.MoveNext() in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerCatalog.cs:line 108
```

**Comment by P-de-Jong** [comment] 2023-09-21 13:04
Went through the code a bit, opened a PR for a fix (:

**Comment by tareqimbasher** [comment] 2023-09-23 16:14
Didn't mean to close. An update will be released asap with this fix.

**Comment by bennich** [comment] 2023-09-25 14:17
I see the same behavior on OSX as well for both the Arm64 and X64 binaries.

`System.PlatformNotSupportedException: OS Architecture 'Arm64' is not supported. OS: (Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020)
   at NetPad.Utilities.PlatformUtil.IsOsArchitectureSupported(Boolean throwIfNotSupported) in /Users/user245337/Downloads/NetPad/src/Core/NetPad.Domain/Utilities/PlatformUtil.cs:line 38
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerDownloader.DownloadAsync(OSPlatform platform) in /Users/user245337/Downloads/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerDownloader.cs:line 50
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerDownloader.DownloadAsync(OSPlatform platform) in /Users/user245337/Downloads/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerDownloader.cs:line 93
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerLocator.GetServerLocationAsync() in /Users/user245337/Downloads/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerLocator.cs:line 41
   at NetPad.Plugins.OmniSharp.Services.AppOmniSharpServer.StartOmniSharpServerAsync() in /Users/user245337/Downloads/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/AppOmniSharpServer.cs:line 132
   at NetPad.Plugins.OmniSharp.Services.AppOmniSharpServer.StartAsync() in /Users/user245337/Downloads/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/AppOmniSharpServer.cs:line 87
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerCatalog.<>c__DisplayClass7_1.<<StartOmniSharpServerAsync>b__1>d.MoveNext() in /Users/user245337/Downloads/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerCatalog.cs:line 108`
   
and 

2023-09-25T16:13:33.7746560+02:00 [ERR] (PID: 26879|NetPad.Plugins.OmniSharp.Services.OmniSharpServerCatalog) Error occurred starting OmniSharp server
System.PlatformNotSupportedException: OS Architecture 'X64' is not supported. OS: (Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020)
   at NetPad.Utilities.PlatformUtil.IsOsArchitectureSupported(Boolean throwIfNotSupported) in /home/tips/Source/TIPS/NetPad/src/Core/NetPad.Domain/Utilities/PlatformUtil.cs:line 38
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerDownloader.DownloadAsync(OSPlatform platform) in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerDownloader.cs:line 50
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerDownloader.DownloadAsync(OSPlatform platform) in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerDownloader.cs:line 93
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerLocator.GetServerLocationAsync() in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerLocator.cs:line 41
   at NetPad.Plugins.OmniSharp.Services.AppOmniSharpServer.StartOmniSharpServerAsync() in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/AppOmniSharpServer.cs:line 132
   at NetPad.Plugins.OmniSharp.Services.AppOmniSharpServer.StartAsync() in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/AppOmniSharpServer.cs:line 87
   at NetPad.Plugins.OmniSharp.Services.OmniSharpServerCatalog.<>c__DisplayClass7_1.<<StartOmniSharpServerAsync>b__1>d.MoveNext() in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/Services/OmniSharpServerCatalog.cs:line 108

**Comment by tareqimbasher** [comment] 2023-09-26 04:07
This issue is going to affect all new installs on all operating systems. It stops downloading OmniSharp if its not already installed, for existing installs this issue won't manifest.

A quick fix until the new update is released (which I'm trying to get out asap) is to download and run v0.4.2 and wait for it to finish downloading OmniSharp. That should fix it, you can then run v0.5.0 without an issue.

**Comment by bennich** [comment] 2023-09-26 09:12
> This issue is going to affect all new installs on all operating systems. It stops downloading OmniSharp if it hasn't already been downloaded, but for existing installs this issue won't manifest.
> 
> A quick fix until the new update is released (which I'm trying to get out asap) is to download and run v0.4.2 and wait for it to finish downloading OmniSharp. That should fix it, you can then run v0.5.0 without an issue.

Awesome - fix confirmed working 👍

**Comment by hbarkine** [comment] 2023-09-28 10:15
Hey! Just came here to check this issue, downloading 0.4.2 made it work. Since I am here thanks for the great work guys. I am a Unity Developer It is sometimes really hard to test things on Unity side when the App gets too big. Kudos!

**Comment by tareqimbasher** [comment] 2023-10-25 01:28
v0.5.1 is out and fixes this issue. Sorry for the delay everyone!

@hbarkine Thank you for the support! Really glad you're enjoying it.

**Closed by tareqimbasher** 2023-10-25 01:28 UTC
Labels: bug
