### ISSUE TITLE
Unable to find dotnet on macOS

### ISSUE THREAD

**Issue by ChristopherHaws** [tareqimbasher/NetPad#42] opened 2023-05-17 06:24 UTC
Hey, I am trying to use NetPad on my M1 macbook pro but it keeps telling me that .NET 6 is not installed or not on my path, but I have verified that it is installed and is in my path.

<img width="845" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/5934505/f0c375fa-2a80-41aa-aa56-f2c228233f68">

**Comment by pa-topo** [comment] 2023-05-17 10:02
I am facing the same problem. 

### Here is my setup: 

```
$ machine 

arm64e

$ uname -a 

Darwin Pauls-Laptop.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
```

### I have the following SDK versions installed. 

```shell
$ dotnet --list-sdks

6.0.403 [/usr/local/share/dotnet/sdk]
6.0.408 [/usr/local/share/dotnet/sdk]
7.0.100 [/usr/local/share/dotnet/sdk]
8.0.100-preview.4.23260.5 [/usr/local/share/dotnet/sdk]
```

### I tried to put the SDK in the PATH but it didn't work. 

```shell
# ~/.zshrc 

export PATH="/usr/local/share/dotnet/sdk/6.0.408/:$PATH"
```

### I tried to run it from the shell, and it didn't work either. 

```
$ dotnet /Applications/NetPad.app/Contents/Resources/bin/NetPad.Apps.App.dll

Failed to load /Applications/NetPad.app/Contents/Resources/bin/libhostpolicy.dylib, error: dlopen(/Applications/NetPad.app/Contents/Resources/bin/libhostpolicy.dylib, 0x0001): tried: '/Applications/NetPad.app/Contents/Resources/bin/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/NetPad.app/Contents/Resources/bin/libhostpolicy.dylib' (no such file), '/Applications/NetPad.app/Contents/Resources/bin/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
An error occurred while loading required library libhostpolicy.dylib from [/Applications/NetPad.app/Contents/Resources/bin/]
```

### I tried creating an alias for version 6 and running it from the shell and it didn't work either. 

```shell
$ alias _dotnet='/usr/local/share/dotnet/dotnet /usr/local/share/dotnet/sdk/6.0.408/dotnet.dll'
$ _dotnet --version 

6.0.408
```

### When I invoke using the alias

```
$ _dotnet /Applications/NetPad.app/Contents/Resources/bin/NetPad.Apps.App.dll

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/Applications/NetPad.app/Contents/Resources/bin/NetPad.Apps.App does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by tareqimbasher** [comment] 2023-05-20 23:04
@ChristopherHaws @pa-topo thank you both for reporting this bug. Can you please verify the value of the `DOTNET_ROOT` environment variable:
```bash
$ echo $DOTNET_ROOT
```

The value of this variable should point to the your dotnet install dir, (ie. `/usr/local/share/dotnet`)

Also @pa-topo, in your sample of setting `PATH`, you want to add the root dotnet directory to your `PATH`, not a specific SDK version directory.

Good:
```bash
export PATH="/usr/local/share/dotnet:$PATH"
```

Bad:
```bash
export PATH="/usr/local/share/dotnet/sdk/6.0.408/:$PATH"
```

**Comment by lpreiner** [comment] 2023-05-22 01:59
I have the same issue.  DOTNET_ROOT was not present in my environment, but the root dotnet directory `(/usr/local/share/dotnet)` is in my PATH.

**Comment by tareqimbasher** [comment] 2023-05-23 18:50
Thank you for the feedback. I will release an update to fix this issue in the next few days. 

@lpreiner are you running on a M1 Mac as well?

**Comment by lpreiner** [comment] 2023-05-23 18:55
> Thank you for the feedback. I will release an update to fix this issue in the next few days. 
> 
> @lpreiner are you running on a M1 Mac as well?

Great!  I'm running an M2 Mac.

**Comment by pa-topo** [comment] 2023-05-25 23:50
> @ChristopherHaws @pa-topo thank you both for reporting this bug. Can you please verify the value of the `DOTNET_ROOT` environment variable:
> 
> ```shell
> $ echo $DOTNET_ROOT
> ```
> 
> The value of this variable should point to the your dotnet install dir, (ie. `/usr/local/share/dotnet`)
> 
> Also @pa-topo, in your sample of setting `PATH`, you want to add the root dotnet directory to your `PATH`, not a specific SDK version directory.
> 
> Good:
> 
> ```shell
> export PATH="/usr/local/share/dotnet:$PATH"
> ```
> 
> Bad:
> 
> ```shell
> export PATH="/usr/local/share/dotnet/sdk/6.0.408/:$PATH"
> ```

Yes, I know, haha. It was a silly thing to do, I just listed what I've tried, so you don't have to. :)

```
echo $DOTNET_ROOT 

```

The environment variable DOTNET_ROOT is not set. Do you want me to try something else? I'll be happy to help.

**Comment by ChristopherHaws** [comment] 2023-05-26 04:16
The environment variable `DOTNET_ROOT` is also not set on my mac. MacOS doesn't have the same concept of globally defined environment variables like on Windows. The normal way you set an environment variable is in `~/.bash_profile` or `~/.zshrc` or the config file for w/e shell you are using. Some apps install a plist file and set it to launch on system boot. [This stackoverflow](https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x) explains it much better than I am.

I think that a better solution would be to allow users to configure a custom install location in the settings screen of the app and having it default to `/usr/local/share/dotnet` when not set. This is how VSCode and JetBrains Rider do it.

Thanks!

**Comment by tareqimbasher** [comment] 2023-05-30 22:10
Alrighty, so I got a side build (v0.3.1) I'd like you guys to try out. I changed how NetPad scans for the correct .NET SDK installation directory and added a setting for users to set a custom install directory path as suggested by @ChristopherHaws. Unfortunately I couldn't test this on macOS ARM; I rented a cloud M1 VM but I couldn't repro the bug.

This is the download link: https://www.swisstransfer.com/d/0d65734a-0607-45cb-ac87-cbef75d29513

For more info, this is what its doing now to get the .NET SDK path, in order of priority:
1. If user has set a custom .NET SDK directory path in settings, that is the directory that will be used. No scanning will be performed. If the path is incorrect or does not exist, it will complain that it can't find a .NET SDK installation.
2. If the setting is empty/unset NetPad will try to invoke the `dotnet` command using the system shell and, if successful, use that location.
3. If that doesn't work, it will then scan the following locations, in this order. The first location that it finds on disk, that also contains the `dotnet` executable will be the path that it uses:
- The path stored in the `DOTNET_ROOT` environment variable, if one exists
- The path stored in the `DOTNET_INSTALL_DIR` environment variable, if one exists
- Windows:
  - `C:\Program Files\dotnet\x64`
  - `C:\Program Files\dotnet`
- macOS/Linux
  - `/usr/local/share/dotnet`
  - `/usr/share/dotnet`
  - `/usr/lib/dotnet`
  - `/opt/dotnet`

**Comment by abrari-ipb** [comment] 2023-05-31 02:49
@tareqimbasher I have tested your latest build in a Mac with Intel chip, and it seems to be working (adding connection, running queries). But autocomplete in the editor does not work (just showing "Loading..." pop-up indefinitely). I don't know if this is related with this issue.

**Comment by tareqimbasher** [comment] 2023-05-31 08:31
@abrari-ipb do you still see that behavior after you restart NetPad? If you do please open a new issue as it is unrelated to this issue.

**Comment by lpreiner** [comment] 2023-06-01 23:17
> Alrighty, so I got a side build (v0.3.1) I'd like you guys to try out. I changed how NetPad scans for the correct .NET SDK installation directory and added a setting for users to set a custom install directory path as suggested by @ChristopherHaws. Unfortunately I couldn't test this on macOS ARM; I rented a cloud M1 VM but I couldn't repro the bug.
> 
> This is the download link: https://www.swisstransfer.com/d/0d65734a-0607-45cb-ac87-cbef75d29513
> 
> For more info, this is what its doing now to get the .NET SDK path, in order of priority:
> 
>     1. If user has set a custom .NET SDK directory path in settings, that is the directory that will be used. No scanning will be performed. If the path is incorrect or does not exist, it will complain that it can't find a .NET SDK installation.
> 
>     2. If the setting is empty/unset NetPad will try to invoke the `dotnet` command using the system shell and, if successful, use that location.
> 
>     3. If that doesn't work, it will then scan the following locations, in this order. The first location that it finds on disk, that also contains the `dotnet` executable will be the path that it uses:
> 
> 
>     * The path stored in the `DOTNET_ROOT` environment variable, if one exists
> 
>     * The path stored in the `DOTNET_INSTALL_DIR` environment variable, if one exists
> 
>     * Windows:
>       
>       * `C:\Program Files\dotnet\x64`
>       * `C:\Program Files\dotnet`
> 
>     * macOS/Linux
>       
>       * `/usr/local/share/dotnet`
>       * `/usr/share/dotnet`
>       * `/usr/lib/dotnet`
>       * `/opt/dotnet`

I finally got a chance to test things out.  I no longer receive the dependency check dialog, but I'm not able to execute queries.  This is what I'm seeing:

Query:
```csharp
var items = new[] {
    "Item A",
    "Item B"
};
items.Dump();
```
Result:
`   at ScriptRuntimeServices.Init()   at Program.<Main>$(String[] args)Unhandled exception. System.TypeInitializationException: The type initializer for 'Program' threw an exception.File name: 'NetPad.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Could not load file or assembly 'NetPad.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.   at Program..cctor()   --- End of inner exception stack trace ---`

**Comment by ChristopherHaws** [comment] 2023-06-02 06:41
Same with me, I am getting the `TypeInitializationException` as well.

**Comment by tareqimbasher** [comment] 2023-06-03 00:35
@lpreiner @ChristopherHaws thank you for reporting back. I kind of expected we'd run into something like that.

To start out, NetPad was built for the `x86` architecture and so far I haven't provided, or tested, an `arm64` version of it. There are multiple issues running the `x86` version on Apple Silicon, least of which is the degraded performance. To get the full experience we'd need to build NetPad for macOS ARM. I have been meaning to get an ARM version of NetPad built and provided with each release but I don't own an Apple Silicon machine. GitHub is [working on](https://github.com/github/roadmap/issues/528) hosted macOS ARM runners, but that's not out yet.

I'm open to offers from M1/M2 mac owners to provide a built version of NetPad whenever a new version is released. If anyone is interested, let me know and we can coordinate. Its pretty easy to package NetPad.

Now back to getting you guys up and running. I rented an cloud M1 VM and built and tested a new version. It seems to work just fine, much faster than the `x86` version too. There are a couple caveats though:
* OmniSharp doesn't seem to work on the VM I'm using. NetPad is downloading the correct ARM version of OmniSharp but when running it, the logs show it fails to load a required lib: `'/usr/local/share/dotnet/x64/host/fxr/6.0.16/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`. It could just be the setup of the VM I'm using. I haven't yet tried to troubleshoot that yet beyond a couple Google searches. Your mileage may vary so try it out (you can find the log files at `~/.local/share/NetPad/Logs`). This effectively means that all OmniSharp-provded features are disabled if it doesn't work for you either (ie. Autocomplete, Syntax Highlighting, CodeLens...etc)
* I built this version for macOS Ventura using the following command:
```
electronize build /target custom "osx.13-arm64;mac" /electron-arch arm64 /manifest electron.manifest.js /PublishSingleFile false
```

If you are using Big Sur or Monterey, let me know and I can build you a version for your OS, or you can feel free to clone the repo and run the above command for your OS from the `src/Apps/NetPad.Apps.App` directory. Just substitute the `osx.13-arm64` part with the correct [macOS RID](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#macos-rids), and be sure you have the latest version of the `electronize` dotnet tool:

```bash
dotnet tool update ElectronNET.CLI -g # or 'install' instead of update if you don't have the tool at all
```

Here is the download link for the `arm64` version built for macOS Ventura: https://www.swisstransfer.com/d/9335b990-bfe0-4a1a-bb5d-d1635ab53dfc

**Comment by tareqimbasher** [comment] 2023-06-06 23:04
@lpreiner @ChristopherHaws have any of you given the last build a spin?

**Comment by ChristopherHaws** [comment] 2023-06-07 04:40
<img width="768" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/5934505/3bba42e3-b65d-4b7d-884f-51537a471dc5">

**Comment by lpreiner** [comment] 2023-06-08 01:55
@tareqimbasher  -- finally got around to trying it.  While the zip extracts properly, I'm unable to run the application at all.  I get the message:

> "NetPad" is damaged and can't be opened.  You should move it to the Trash.

**Comment by tareqimbasher** [comment] 2023-06-09 10:37
@ChristopherHaws @lpreiner thank you both for all your feedback. New native macOS ARM builds are almost ready and will be published soon. 

I figured out the issue with Omnisharp for ARM builds and new release will include the fix. For now, if you want to fix it, you can set the environment variable `DOTNET_ROOT` to your .NET SDK root install path.

**Comment by sonerfromnurland** [comment] 2023-06-16 20:28
> 

Waiting for impatiently.

**Comment by tareqimbasher** [comment] 2023-06-17 11:48
New macOS ARM builds are now available in the latest [v0.3.1 release](https://github.com/tareqimbasher/NetPad/releases/tag/v0.3.1)!

That took a bit longer than I would've liked. OmniSharp was having a hard time finding the .NET SDK installation on macOS ARM in some instances. Should all be good now.

I am closing this issue, please feel free to reopen it if you still experience issues.

cc: @ChristopherHaws @lpreiner @abrari-ipb @sonerfromnurland @pa-topo 

--
Please :star2: the repo if you like NetPad!

**Closed by tareqimbasher** 2023-06-17 11:48 UTC
Labels: bug

**Comment by tareqimbasher** [comment] 2023-06-20 00:24
@ChristopherHaws @lpreiner @pa-topo just wanted to check in and see how the new ARM build is working for you guys? Trying to reproduce a bug as mentioned in #47 but I don't want to be chasing a ghost here.

At the very least knowing its working fine (or not) for you might help me determine any cause for issues. Currently, on my cloud macOS ARM machine its working pretty well.

Any feedback is greatly appreciated. Thanks!

**Comment by lpreiner** [comment] 2023-06-22 04:10
@tareqimbasher -- with the latest published build, I'm able to reproduce the startup hang behavior described in #47.  I can add details for my experience over there.
