### ISSUE TITLE
Roslyn warning text is garbled in the Korean Windows environment

### ISSUE THREAD

**Issue by rkttu** [tareqimbasher/NetPad#187] opened 2024-04-07 07:57 UTC
<img width="1470" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/1297346/f13949ee-e327-413c-8bf8-1e955cd03055">

I'm getting broken Roslyn warning statements in my Korean Windows environment.

Here are the intl.cpl settings that I'm currently using.

- Current User
  - Display Language: Korean
  - Input Language: Korean (South Korea) - Microsoft IME
  - Format: Korean (South Korea)
  - Location: Korea
- Start Screen
  - Display Language: English (United States)
  - Input Language: English (United States) - US
  - Format: English (United States)
  - Location: United States
- New User Account Default
  - Display Language: English (United States)
  - Input Language: English (United States) - US
  - Format: English (United States)
  - Location: United States
- System Locale
  - Korean (South Korea)
  - Beta: Use Unicode UTF-8? - No

**Comment by tareqimbasher** [comment] 2024-04-23 22:20
Thanks for the details. Closing as duplicate of #129 and will be tracked there.

**Closed by tareqimbasher** 2024-04-23 22:20 UTC

**Comment by tareqimbasher** [comment] 2024-04-23 22:21
Duplicate of #129
