### ISSUE TITLE
The dotnet-ef tool is not functioning properly on NetPad on macOS.

### ISSUE THREAD

**Issue by darwin-z** [tareqimbasher/NetPad#78] opened 2023-08-17 14:14 UTC
I've already set up the .NET SDK and installed the dotnet-ef tool. It runs fine in the local command line. However, on the App Dependencies Check page, it shows that the .NET SDK is installed successfully, but dotnet-ef displays "Entity Framework Core .NET tool is not installed."
<img width="739" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/f1bc09f5-0864-4057-bbf6-34ee037e608b">
<img width="721" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/6af2c576-0124-454b-b9dc-a55365043ad6">
<img width="579" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/99dd1abc-6cb5-4ed1-8994-e075ae0e52b6">
<img width="605" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/8aa91635-f527-4271-8952-a5bde79ee81d">
<img width="1339" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/07e2c484-1305-43ab-a158-e15ec3000e17">

**Comment by tareqimbasher** [comment] 2023-08-18 15:42
Also I noticed in the StackTrace your last screenshot that it seems you've built NetPad from source? If so, were you seeing the same exact error when using the prebuilt binary?

**Comment by 2hangha1fen9** [comment] 2023-08-20 14:42
I downloaded NetPad(v0.4.2) from the Release.

<img width="844" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/f2eaa169-24f5-450e-a16f-bce76ba6b37e">



So far, I have found that executing it on my local command line with root privileges has the same issue.

#### Normal state（`dotnet --info`,`dotnet-ef`）

<img width="761" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/dc0fc749-0b8d-4c05-a1c4-879ee5fbdcc2">
<img width="605" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/033cbc1e-7151-42e3-b91a-e0da4880b50f">



#### Executing with `sudo` （`sudo dotnet --info`,`sudo dotnet-ef`）

<img width="733" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/c1f73f74-124e-49aa-80ac-43d09840e122">

>  ` Environment variables` display as `Not Set`

<img width="875" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/273d54b2-e61e-401f-a167-927784d4c316">



However, when I use `sudo -E` to preserve the current environment variables, the result is the same as executing directly.

#### `sudo -E dotnet-ef --info` and `sudo -E dotnet-ef`

<img width="723" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/0e280e81-c17c-4c42-b04c-a73133fbeeb4">

<img width="593" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/3aea31fd-710b-4f55-aac8-623d33987a99">



I took a rough look at your code, and regarding the operations involving `Process.Start`, it seems that user environment variables are not being passed, which might be causing the absence of these variables. Perhaps some modifications are needed here.

<img width="912" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/1a022a35-4c33-4791-a303-d351c3f9d277">

**Comment by tareqimbasher** [comment] 2023-08-20 22:50
Yep that's exactly what the problem is. Thank you for taking the time and digging and providing all that great info, makes my job that much easier! 😄

I think there's a couple more places where I need to pass along the env variables, and the one you pointed to is one of them.

Should have a patch for this soon. Did you use the standard installer from Microsoft to install the .NET SDK or did you use a package manager like homebrew? Trying to account for the different install pathways users might choose.

**Comment by 2hangha1fen9** [comment] 2023-08-21 03:20
I use the official [dotnet-install.sh](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) installation script to install the .NET SDK, it defaults to installing it in my home directory.

**Comment by tareqimbasher** [comment] 2023-09-07 01:24
**Update:** #84 is merged and will fix this issue. It will go out in v0.5.0. I also added `~/.dotnet` as a common directory that NetPad will search within for a .NET SDK installation, so you will be able to remove the manual .NET SDK path you set in settings.

**Comment by tareqimbasher** [comment] 2023-09-18 10:25
@2hangha1fen9 v0.5.0 is out, can you please verify your issue is resolved.

**Comment by 2hangha1fen9** [comment] 2023-09-18 12:19
> @2hangha1fen9 [v0.5.0](https://github.com/tareqimbasher/NetPad/releases/tag/v0.5.0) is out, can you please verify your issue is resolved.

It's working now, but the dependency detection dialog is not displaying correctly.👍
<img width="1170" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/102583750/458e5a51-fc23-487b-95a6-abadd0aa74f6">

**Comment by tareqimbasher** [comment] 2024-05-20 19:31
@darwin-z a couple versions of NetPad have been released since the last update here. Are you still experiencing this issue?

**Closed** 2024-07-09 00:59 UTC
Labels: bug
