### ISSUE TITLE
Console.WriteLine(char value) overload not displaying in Results Panel

### ISSUE THREAD

**Issue by xgdoggiex** [tareqimbasher/NetPad#225] opened 2024-07-01 19:46 UTC
Hello!

I appear to be having an issue displaying the output of the below example code in NetPad:
```
char a = 'I';
Console.WriteLine("Printing a char");
Console.WriteLine(a);
```

 It appears as though using the `Console.WriteLine(char value)` overload does not print anything to the Results pane:

![NetPad Screenshot](https://github.com/tareqimbasher/NetPad/assets/136862092/838d303f-a12f-4824-b134-6fd84f1d1b4d)

**NetPad Version**: v0.7.1

**Comment by tareqimbasher** [comment] 2024-07-01 22:19
Thank you for reporting, I'll get this fixed.

**Comment by SimonNyvall** [comment] 2024-08-08 16:17
Have done some digging into the problem.

In the `ExternalScriptRunner.cs` a process runs the dotnet application and the output ends up in **OnProcessOutputRecevied** 
``` json
{
    "type":"HtmlResultsScriptOutput",
    "output": {
        "body":"<div class="group text"><br/></div>",
        "order":1
    }
}
```

although the only chars gets parsed weired. Have not checked the dll that gets generated in the tmp/Processes, may be an issue there

**Comment by tareqimbasher** [comment] 2024-08-08 18:17
@SimonNyvall thanks for digging in. The issue is most likely in the [ActionTextWriter](https://github.com/tareqimbasher/NetPad/blob/main/src/Core/NetPad.Runtime/ExecutionModel/External/Interface/ActionTextWriter.cs) which derives from `TextWriter`. There I'm overriding `Write(string value)` and `WriteLine(string value)` but when writing a `char` it doesn't go through that method and most likely goes through `WriteLine(char value)`. We can override all the overloads from `TextWriter` but I don't think we need to. Instead we can only override a select few that all the other overloads eventually funnel to.

I imagine `WriteLine(char value)` will have to be overridden since if I had to guess it would be one of those terminal functions that won't call another overload.

**Comment by tareqimbasher** [comment] 2024-08-08 19:24
That's great! Go ahead and submit a PR. Thanks for working on this.

**Comment by tareqimbasher** [comment] 2024-08-11 22:51
PR #240 is merged and fixes this issue. Thank you @SimonNyvall

**Closed by tareqimbasher** 2024-08-11 22:51 UTC
Labels: bug
